version: '3'
services:
  mysql:
    image: "mysql:5.7"
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root


  adp:
    image: "dineshsonachalam/adp:1.0.0"
    depends_on:
      - mysql
    networks:
      - frontend
    restart: always
    ports:
      - "8006:8006"

networks:
  frontend: