version: '3'
services:
  mysql:
    image: "mysql:5.7"
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=simple
      - MYSQL_DATABASE=adp


networks:
  frontend: